# ================================
# GCP Metadata
# ================================
project_id: "<REPLACE-YOUR-ID-THERE>"
region: "asia-southeast1"
service_name: "GDGoC-UIT | Image Search"

# ================================
# Storage Settings
# ================================
bucket_name: "gdgoc_uit_cloudsharing"
keywords_file: "keywords.json"
upload_folder: "images/"

# ================================
# Server Settings
# ================================
host: "0.0.0.0"
port: 8080
debug: true
allowed_extensions: ["jpg", "jpeg", "png", "gif"]